ibm-id:
  resource-server:
    jwk-certificate-path: /IBM-ID-JWK-CERT/prepiam_toronto_ca_ibm_com.crt
    client-id: OTQxYTAyOTUtYWNlOS00
    client-secret: MWM2N2M2N2UtYzY4Yi00
    token-introspection-endpoint: https://prepiam.toronto.ca.ibm.com/idaas/oidc/endpoint/default/introspect
    system-partners:
      - OWNiNzU1OTctMzAwOC00
ram-guards:
  authorization-server:
    client-id: danube-zuul
    client-secret: LwitblTK4KgOInkWh/0bpsFjdxdM8sguAVtA0eLG0fI=
    default-password: default-password
  zuul:
    authorization-server-service-id: service-authorize

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
logging:
  level:
    root: debug
spring:
  application:
    name: service-zuul
zuul:
  routes:
    authorize:
      path: /authorize/**
      serviceId: service-authorize
      sensitiveHeaders: Cookie,Set-Cookie
    client:
      path: /client/**
      serviceId: service-hi
      sensitiveHeaders: Cookie,Set-Cookie
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 12000

